# Dockerfile.dev
FROM mcr.microsoft.com/dotnet/sdk:8.0  AS build

WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends <paket> && rm -rf /var/lib/apt/lists/*

COPY  *.sln ./
COPY  **/*.csproj ./
RUN dotnet restore

COPY . ./

ENV DOTNET_USE_POLLING_FILE_WATCHER=1
EXPOSE 5000 5001

CMD ["dotnet", "watch", "run", "--urls", "http://0.0.0.0:5000;https://0.0.0.0:5001"]